deployment:
  tasks:
    - echo "Starting deployment..."

    # Frontend: Install dependencies and build React app
    - echo "Setting up frontend"
    - cd $DEPLOYMENT_SOURCE
    - npm install
    - npm run build

    # Deploy frontend static files to public_html
    - echo "Deploying frontend to public_html"
    - rm -rf /home/megruhsm/public_html/*
    - cp -r build/* /home/megruhsm/public_html/

    - echo "Deployment finished successfully!"
